### ISSUE TITLE
how to do synthesis

### ISSUE THREAD

**Issue by regehr** [google/souper#112]
Code synthesis is the next major piece of work for Souper. For each iN in a program, Souper wants to see if it can be computed more cheaply. These are its building blocks:
1. synthesized constants, including undef
2. variables from the LHS
3. instructions
Souper already knows how to do 1 (though not undef yet). 2 is easy. 3 is the main trick. Here's how we'll do it.

We start out with a cost function. Although you can imagine many ways to do this, to a first approximation the cost of a RHS will be the number of instructions. So 1 and 2 in the list above represent zero-cost replacements. The set of cost-1 replacements is just the collection of LLVM instructions that input one or more synthesized constants and LHS variables, and output the desired iN, under the constraint that the LLVM type system is happy. Mostly the type system just wants bitwidths to match up, so for example if we're synthesizing an i32, there's no way that an icmp instruction can produce it. Another constraint is that we don't want to try to synthesize anything that will trivially constant-fold, such as a zext with a constant input or an add with two constant inputs.

Given a cost function, we batch up solutions in such a way that our first query will succeed iff there exists a cost-0 replacement, our second query will succeed iff there's a cost-1 replacement, etc. We issue these queries sequentially and stop when we find a solution (which is guaranteed to be the cheapest one) or else we get bored. It is easy to see that as the cost increases, the number of possible solutions grows exponentially. We need a way to prevent the query size from exploding. This slide deck outlines an encoding that will probably work for us:

http://www.eecs.berkeley.edu/~jha/pres/pldi11.pdf

The idea is to push the exponential search into the solver (which is doing a huge search anyway, so why not get it to consider a few more bits of search space).

**Comment by rsas** [comment]
I think my patch #167 is ready for the initial review. Please give the synthesis a try and let me know if you encounter any problems. You must use z3 or any other solver that produces models.

**Comment by rsas** [comment]
Implemented in 21ed266.
