### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by regehr** [google/souper#154]
I think we have a nasty bug. The checked_add_4() function in the code below is -- I believe -- a solid implementation of a 32-bit addition that checks for signed overflow. Souper proves that it always returns 0, which is nonsense. Here's the optimization:

```
%0 = block 3
%1:i32 = var
%2:i1 = slt 0:i32, %1
blockpc %0 0 %2 1:i1
%3:i32 = subnsw 2147483647:i32, %1
%4:i32 = var
%5:i1 = slt %3, %4
blockpc %0 0 %5 1:i1
%6:i1 = slt %1, 0:i32
blockpc %0 1 %6 1:i1
%7:i32 = subnsw 2147483648:i32, %1
%8:i1 = slt %4, %7
blockpc %0 1 %8 1:i1
%9:i32 = phi %0, 1:i32, 1:i32, 0:i32
cand %9 0:i32
```

I believe something has gone wrong here. The full code is below.  It is supposed to print "-202 1", but when compiled with souper it prints "-202 0".

```
#define MIN ((int)(1U<<31))
#define MAX ((int)((1U<<31)-1))

int checked_add_4(int a, int b, int *rp) {
  if (b > 0 && a > MAX - b) {
    *rp = (a + MIN) + (b + MIN);
    return 1;
  }
  if (b < 0 && a < MIN - b) {
    *rp = (a - MIN) + (b - MIN);
    return 1;
  }
  *rp = a + b;
  return 0;
}

#ifdef TEST

#include <limits.h>
#include <assert.h>
#include <stdio.h>

int main (void)
{
  assert(MIN==INT_MIN);
  assert(MAX==INT_MAX);
  volatile int x = INT_MAX - 100;
  volatile int y = INT_MAX - 100;
  int r, o;
  o = checked_add_4(x, y, &r);
  printf ("%d %d\n", r, o);
  return 0;
}

#endif
```

**Comment by regehr** [comment]
I'm invoking sclang like this:

```
sclang -O3 foo.c
```

Here are my environment variables:

```
SOUPER_DEBUG=1
SOUPER_INFER_NOP=1
SOUPER_NO_INFER_I1=1
SOUPER_SOLVER=-z3-path=/usr/bin/z3
```

**Comment by rsas** [comment]
Which branch are you using? You are guessing a nop, right? I cannot reproduce the result. If I try to infer %9 in the opt above, no RHS is found.

**Comment by regehr** [comment]
I get the same result using constant inference or nop inference. I'm using my synthesis-pass-support branch.

**Comment by regehr** [comment]
Below is the Souper annotated with C-level information. All looks good to me.

```
%0 = block 3
%1:i32 = var                            b
%2:i1 = slt 0:i32, %1                   0 < b
blockpc %0 0 %2 1:i1                    b > 0 if we come from pred 0
%3:i32 = subnsw 2147483647:i32, %1      INT_MAX - b
%4:i32 = var                            a
%5:i1 = slt %3, %4                      (INT_MAX - b) < a
blockpc %0 0 %5 1:i1                    a > (INT_MAX - b) if we come from pred 0
%6:i1 = slt %1, 0:i32                   b < 0
blockpc %0 1 %6 1:i1                    b < 0 if we come from pred 1
%7:i32 = subnsw 2147483648:i32, %1      INT_MIN - b
%8:i1 = slt %4, %7                      a < (INT_MIN - b)
blockpc %0 1 %8 1:i1                    a < (INT_MIN - b) if we come from pred 1
%9:i32 = phi %0, 1:i32, 1:i32, 0:i32
cand %9 0:i32
```

**Comment by regehr** [comment]
I wonder if blockpc is somehow mixing up UB predicates from the different branches?

**Comment by rsas** [comment]
I reproduced it on master with constant inference, investigating.

**Comment by rsas** [comment]
It's definitely something nasty with predicates and UB constraints. @chenyang78 added the block pc constraint handling code, I'll have analyze it first.

**Comment by chenyang78** [comment]
I will investigate it over the weekend, if it's not in hurry. Sorry for introducing the bug.

**Comment by rsas** [comment]
It's not clear if it's your bug or not. I'll let you know if I won't find anything today/tomorrow.

**Comment by regehr** [comment]
No rush, I'm just happy I found an understandable testcase for it. Until tonight I had been on the trail of this one for several days without luck.

**Comment by chenyang78** [comment]
Thanks Raimondas.

**Comment by chenyang78** [comment]
I see what's going wrong here. I will send a bug-fix request soon.
