### ISSUE TITLE
OOM in getUBPhiPaths

### ISSUE THREAD

**Issue by regehr** [google/souper#218]
While building current LLVM, getUBPhiPaths recurses to depth ~1000, eventually exhausting RAM on the machine I'm using. I've read the code and we already have some attempts to use less resources in this part of Souper. My current thought is that we simply permit Souper to fail (by bailing on this particular expression) when such a large depth of phi nodes is found, what do people think?

**Comment by chenyang78** [comment]
Yes, this part was optimized for resource usage, but looks like the optimization is not good enough for building current LLVM. The approach that you proposed is fine to me.

**Comment by regehr** [comment]
Fixed.
