### ISSUE TITLE
Build error. OS X 10.11.5

### ISSUE THREAD

**Issue by chadbrewbaker** [google/souper#219]
[ 98%] Building CXX object CMakeFiles/souperweb-backend.dir/tools/souperweb-backend.cpp.o
souper/tools/souperweb-backend.cpp:36:53: error: use of undeclared identifier
      'getGlobalContext'
          parseAssembly(MB->getMemBufferRef(), Err, getGlobalContext())) {
                                                    ^
1 error generated.

**Comment by jeroenk** [comment]
getGlobalContext was removed from LLVM a while back, so this probably broke in the last LLVM bump.

**Comment by regehr** [comment]
Yeah, I think this got missed since souperweb only gets built when Go is installed or something like that -- I'll look into it tonight.

**Comment by regehr** [comment]
Should be fixed-- thanks for the bug report!

**Comment by rgov** [comment]
Built fine for me on 10.12 beta. I think this issue can be closed.
