### ISSUE TITLE
Bump to LLVM 3.9

### ISSUE THREAD

**Issue by rgov** [google/souper#227]
With the imminent release of LLVM 3.9, Souper should be updated to build with the latest LLVM sources.

**Comment by regehr** [comment]
It may be time to stabilize against LLVM releases instead of trying to track head. Early on, we had to update often to take advantage of bugfixes but I don't think that's true any longer.

**Comment by regehr** [comment]
I'm out this weekend but will bump to 3.9 asap, and we can leave souper there for a while.
