### ISSUE TITLE
another nop issue

### ISSUE THREAD

**Issue by regehr** [google/souper#307]
Here's one that gets miscompiled by sclang -O2 with nop synthesis:
```
int printf(const char *, ...);
int a = 48;
void b(int *c, char d) {
  char e = d >= 32 ? 10 : 10 >> d;
  if (e)
    *c = 0;
}
int main() {
  b(&a, a);
  printf("%d\n", a);
}
```
The program is defined and should print 0, but Souper makes it print 48.

Souper performs a single optimization which is, I believe, correct:
```
%0:i8 = var
%1:i32 = sext %0
%2:i32 = lshr 10:i32, %1
%3:i8 = trunc %2
%4:i1 = ne 0:i8, %3
%5:i1 = slt 31:i8, %0
%6:i1 = or %4, %5
cand %6 %4
```
As long as Souper's optimization is correct then the problem will come down to LLVM having done something wrong that Souper is exposing. These are no fun to track down in general, but this example looks easy.
Can you look into this @zhengyangl?

**Comment by zhengyangl** [comment]
Sure.

**Comment by zhengyangl** [comment]
I believe this transformation is wrong, it tries to transform

`if (d > 31 || (10 >> d))` into `if (10 >> d)`

**Comment by zhengyangl** [comment]
Take %0 = 40 as example, %4 = false, %5 is true, %6 is true, in this case %4 != %6. I am trying to figure out why souper and alive thinks this transformation is valid.

**Comment by regehr** [comment]
Can you post the full code before and after this one?

**Comment by regehr** [comment]
If d == 40 then the behavior of the shift is undefined and any RHS is OK (as long as you don't use a short-circuiting ||, which isn't clear from the example).

**Comment by regehr** [comment]
link to rise4run/Alive please!

**Comment by zhengyangl** [comment]
IR Before Souper
```llvm
define void @b(i32* %c, i8 signext %d) local_unnamed_addr #0 {
entry:
  %conv = sext i8 %d to i32
  %cmp = icmp sgt i8 %d, 31
  %shr = lshr i32 10, %conv
  %0 = trunc i32 %shr to i8
  %tobool5 = icmp ne i8 %0, 0
  %tobool = or i1 %cmp, %tobool5
  br i1 %tobool, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  store i32 0, i32* %c, align 4, !tbaa !2
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}
```

**Comment by zhengyangl** [comment]
IR After Souper
```llvm
define void @b(i32* %c, i8 signext %d) local_unnamed_addr #0 {
entry:
  %conv = sext i8 %d to i32
  %cmp = icmp sgt i8 %d, 31
  %shr = lshr i32 10, %conv
  %0 = trunc i32 %shr to i8
  %tobool5 = icmp ne i8 %0, 0
  %tobool = or i1 %cmp, %tobool5
  br i1 %tobool5, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  store i32 0, i32* %c, align 4, !tbaa !2
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  ret void
}
```

**Comment by zhengyangl** [comment]
Permalink to rise4fun/alive: https://rise4fun.com/Alive/sl0

**Comment by zhengyangl** [comment]
I found the error transformation in InstCombine, by disable this transformation, souper nop infer works correctly in this case.

```diff
Index: lib/Transforms/InstCombine/InstCombineSelect.cpp
===================================================================
--- lib/Transforms/InstCombine/InstCombineSelect.cpp    (revision 313611)
+++ lib/Transforms/InstCombine/InstCombineSelect.cpp    (working copy)
@@ -1183,10 +1183,12 @@

   if (SelType->isIntOrIntVectorTy(1) &&
       TrueVal->getType() == CondVal->getType()) {
+    #if 0
     if (match(TrueVal, m_One())) {
       // Change: A = select B, true, C --> A = or B, C
       return BinaryOperator::CreateOr(CondVal, FalseVal);
     }
+    #endif
     if (match(TrueVal, m_Zero())) {
       // Change: A = select B, false, C --> A = and !B, C
       Value *NotCond = Builder.CreateNot(CondVal, "not." + CondVal->getName());
```

**Comment by regehr** [comment]
Great.  Please also disable the next one -- I can see it will cause the 
same problem, and look for any more lowering of select to logic, which 
will always cause this problem when the not-selected branch is poison.

John

**Comment by zhengyangl** [comment]
Note this transformation is not necessarily wrong, during the instcombine, the original select is erased and a new select is generated, and commenting out these lines only blocks the transformation on the generated one. I need time to figure out if any other transformation is illegal.

**Comment by zhengyangl** [comment]
@regehr Sure.

**Comment by nunoplopes** [comment]
@regehr There maybe half a dozen broken select-related optimizations. The good news is that all the other non-select-related optimizations were fine last time I checked.

**Comment by regehr** [comment]
Thanks Nuno!

**Comment by zhengyangl** [comment]
Thanks Nuno! John: What do you think about fixing this? How about add a patch and let update_deps.sh apply the patch after fetching llvm?

**Comment by regehr** [comment]
Yes, exactly. You can do this in my llvm6 branch. Once you've patched out the select i1 -> logic transformations I'll resume stress-testing.

**Comment by zhengyangl** [comment]
@regehr sure.

**Comment by regehr** [comment]
Ok, we seem to have a working (but sucky) solution to this in a branch that'll get merged once LLVM 6 is released, so I'm going to go ahead and close. Of course the right answer is to fix LLVM.
