### ISSUE TITLE
Another useless variable: ExprBuilderContext::InstMap

### ISSUE THREAD

**Issue by zhengyangl** [google/souper#318]
I found this when I was trying to add the external use tagging support to the extractor, I believe this map variable is designed to cache the result Inst. But since there are no map insertions, this variable is useless. The only use of this variable is here:

https://github.com/google/souper/blob/8d8910b053b1d3128e538786e616ad91ba2eb10c/lib/Extractor/Candidates.cpp#L508

I've double checked there are no other uses.

John: can I remove this variable?

**Comment by regehr** [comment]
I think that is a good idea.

Please also take a look at VarInstsByWidth while you're here, and if that also needs to be removed, prepare a PR with both changes.

**Comment by regehr** [comment]
Actually, wait. I believe map[v] is side-effecting, it adds an entry into the map. Perhaps that's what is intended here. Please look at this very carefully before proposing a change.

**Comment by zhengyangl** [comment]
Oh, you're right.

**Comment by zhengyangl** [comment]
I'll have a look at VarInstsByWidth.

**Comment by zhengyangl** [comment]
The VarInstsByWidth works similarly to ExprBuilderContext::InstMap.

**Comment by regehr** [comment]
Can you make a PR adding a quick comment at each of these places so we don't forget about this?
