### ISSUE TITLE
Are utils/ bitrot?

### ISSUE THREAD

**Issue by LebedevRI** [google/souper#334]
`cache_dump` does not work out-of-the box
```diff
-    my %h = $r->hgetall($opt);
+    my %h;
+    if($r->TYPE($opt) eq "hash") {
+      %h = $r->hgetall($opt);
+    } else {
+      next;
+    }
```
`souper2llvm` seems to always generate invalid IR
Is there some other tools that are supposed to be used?

**Comment by regehr** [comment]
cache_dump works out of the box for me, I was just using it yesterday. You'll need to provide standard bug report information (your platform details, steps to reproduce, observed output, etc.) for us to figure out why it isn't working for you.

souper2llvm is more of a research tool and not really something that we want to support, and it contains a bunch of known bugs. I'd suggest not relying on it for now. It was written by @rsas but he probably doesn't have time to support it at the moment.

**Comment by rsas** [comment]
Hi @LebedevRI, as mentioned by @regehr, ``souper2llvm`` was created a while ago for testing purposes and was not updated/maintained since. It should not be difficult to update/fix it. Contributions are very welcome.

**Comment by LebedevRI** [comment]
> cache_dump works out of the box for me

That is interesting. The reproduction steps are trivial.
1. This is debian sid, fully updated. 
```
 dpkg -l | grep redis
ii  libredis-perl                                    2:1.9910-1                                             all          persistent key-value database with network interface (Perl client library)
ii  redis                                            5:4.0.10-1                                             all          Persistent key-value database with network interface (metapackage)
ii  redis-server                                     5:4.0.10-1                                             amd64        Persistent key-value database with network interface
ii  redis-tools                                      5:4.0.10-1                                             amd64        Persistent key-value database with network interface (client)
```
2. Clone this repo. (i'm at b41a0944c0f0c5b106c71f0ba390290f6ef07b2c)
3. Run `$ ./build_deps.sh` without arguments
4. `$ mkdir souper_build && cd souper_build && cmake -DTEST_SOLVER="-z3-path=/usr/bin/z3" -GNinja ../ && ninja`
5. `$ redis-cli flushall`
6. Build something with `sclang` with `SOUPER_DYNAMIC_PROFILE` and `SOUPER_STATIC_PROFILE` set.
7. Run `./cache_dump`, and it fails with
(i apologize, this is from memory, i butchered the build at the moment):
`error "WRONGTYPE Operation against a key holding the wrong kind of value"`, pointing to the line `195` of `cache_dump`. Application of the patch from the first comment fixes it.

So nothing special at all, pretty much as per the README..

> as mentioned by @regehr, souper2llvm was created a while ago for testing purposes and was not updated/maintained since.

Thank you for this info.
I was surprised given that it is the tool that is used by the `-triage` switch of the `cache_dump` script.

**Comment by LebedevRI** [comment]
> Again, this software is the basis for active research and as such contains plenty of dead ends.

No, i totally understand. Thank you for working on this amazingly unique software!

> I'll apply the cache_dump patch but I'm surprised that it is necessary, perhaps something on your machine placed keys into your redis following the flushall?

I'll double-check tomorrow, but i don't think so.

**Comment by regehr** [comment]
Thanks. Also we'd love to hear what you're using Souper for, and might be able to help out somehow.

Note that synthesis and (even more so) pass support for synthesis is an active area of work for us and we may be able to help if we know more.

**Comment by LebedevRI** [comment]
> Thanks. Also we'd love to hear what you're using Souper for, and might be able to help out somehow.

Thanks. Nothing earth-shattering.
Basically the same as https://blog.regehr.org/archives/1192 - build [some project](https://github.com/darktable-org/rawspeed) i care about with Souper,
analyze the results, possibly try to implement some low hanging fruits/missing optimizations in LLVM.

**Comment by regehr** [comment]
Nice. Synthesizing optimizations turns out to be pretty sensitive to choice of command line options. @rsas did 100% of the synthesis work and may be able to help out.

**Comment by LebedevRI** [comment]
Uhm, this is weird. I have re-done everything from scratch, like i did the first time,
but the `cache_dump` problem no longer reproduces. I'm thinking it may be causable
by killing of the sclang/built binary w/ dynamic profiles.
No point in keeping this open, at least now.

Thanks everyone.

**Comment by regehr** [comment]
That is weird. But also I realized that I haven't used dynamic profiling for quite a while and I should try it more, I'm not sure that code is all that robust.

Keep in mind also that there are some limits to Souper's static and dynamic profiling: they are tracking the popularity of specific souper optimizations, which may or may not correlate well (often not) with the usefulness of the (usually) much more general version that you would actually implement in InstCombine or whatever. There's some sort yet to be done on automated generalization of optimizations.

**Comment by LebedevRI** [comment]
> Hi @LebedevRI, as mentioned by @regehr, `souper2llvm` was created a while ago for testing purposes and was not updated/maintained since. It should not be difficult to update/fix it. Contributions are very welcome.

I was wondering, is there some long-term pre-existing plan for such utility?
Will there be some deeper integration with alive2,
in the sense that such tool should be provided by alive2?
If not, would it perhaps make more sense to re-write this util as a more proper tool (using LLVM API?), possibly with tests?

**Comment by manasij7479** [comment]
I have one potential use case for such an API, especially if it was reasonably fast and could generate LLVM Functions from Souper instructions in-process.   
It would give us a nice way of calling LLVM analysis functions (computeKnownBits) and passes (LVI? SCEV?). I am implementing some of this on Souper IR, but that approach doesn't scale. It would also become necessary once we start dealing with memory, so we do not have to implement alias analysis ourselves.

**Comment by regehr** [comment]
Hi Roman... souper2llvm is an interesting case. It has served uses for us (and continues to) but really it's the wrong approach to do this all in a separate language. If we want to move forward with this tool, my inclination would be to start with the LLVM-building code that we already have in the opt pass and extend that to be more generally useful and powerful. With that said, I'm not sure if we have a lot of compelling use cases for that functionality, though as Manasij says we can think of some if we stretch a bit.

**Comment by LebedevRI** [comment]
In my mind, there is no question whether that tool is useful or not.
It is already used by `cache_dump`. That is my main interest, and main unscratched itch,
to have a sane way to comb through the souper opts, filter only these LLVM does not know about.

> I have one potential use case for such an API, especially if it was reasonably fast and could generate LLVM Functions from Souper instructions in-process.

Can't say anything about fast (i wouldn't think it will necessarily be horrendously slow?), but sure,
splitting the implementation so that it can be used outside of the conversion tool totally makes sense.

**Comment by LebedevRI** [comment]
Oh, i almost missed this, souper already can produce llvm ir, via `SouperPass::getValue()`.
Naturally, that won't produce the whole module though.

**Comment by regehr** [comment]
yes, I think the question is whether it makes sense to factor that code out, so it can be used by both the pass and also the souper2llvm utility

the missing code (create a module with an empty function etc.) is pretty straightforward

converting souper without phi, path conditions, and blockpc into LLVM also seems very easy

converting phi, path conditions, and blockpc into LLVM Ir seems quite a bit more involved....

**Comment by LebedevRI** [comment]
> yes, I think the question is whether it makes sense to factor that code out, so it can be used by both the pass and also the souper2llvm utility

It does, because currently `souper2llvm` is broken (:
It is likely best to have one common path rather than having a perl script that _tries_ to
convert textual souper into llvm ir.
