### ISSUE TITLE
Incorrect handling on intrinsic arguments

### ISSUE THREAD

**Issue by mshockwave** [google/souper#553]
Hi,

In [line 535](https://github.com/google/souper/blob/master/lib/Extractor/Candidates.cpp#L535) of `lib/Extractor/Candidates.cpp`, not every intrinsic functions have at least one argument. Thus sometime it will crash due to out-of-bound argument fetching.

I think we should be more generalized here by either checking the amount of operands or fetching intrinsic arguments only when needed.

Thank you

**Comment by manasij7479** [comment]
Good catch, thanks.
Feel free to send a PR.

**Comment by mshockwave** [comment]
@manasij7479  thanks, I've just sent a PR

**Comment by regehr** [comment]
thanks!! we'll review soon.
