### ISSUE TITLE
[seek help] fail to build dependencies at macOS

### ISSUE THREAD

**Issue by jianguda** [google/souper#605]
Hey, I am following `README.md` to build souper locally, but fail at the very first step.

I run `./build_deps.sh` and here is the last part of my build log:
```
[ 86%] Built target ir
[ 89%] Generating tools/alive_lexer.cpp
make[2]: RE2C-NOTFOUND: No such file or directory
make[2]: *** [tools/alive_lexer.cpp] Error 1
make[1]: *** [CMakeFiles/alive.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Linking CXX shared library libalive2.dylib
[ 91%] Built target alive2
make: *** [all] Error 2
```

Could you please give me some advice? Thanks!

**Comment by jianguda** [comment]
In case it helps:
my LLC's version is 8.0.1
my GCC's version is 9.2.0
my CMake's version is 3.15.3

**Comment by manasij7479** [comment]
Hi, you need to install re2c.
If you use brew: https://brewformulas.org/Re2c
You can also build and install it yourself: https://re2c.org/install/install.html

**Comment by jianguda** [comment]
Thanks! It works!
