### ISSUE TITLE
In order to run /lib/Pass/Pass.cpp seperately flags required ?

### ISSUE THREAD

**Issue by shrin18** [google/souper#627]
We are trying to get successful candidates for .opt file and later get them in .ll What flags shoudl we pass in pass.cpp inside lib/Pass/Pass.cpp in order to achieve this. Thanks!

**Comment by regehr** [comment]
Hi!
Based on this description, I have no clue at all what you are trying to accomplish using Souper, please provide significantly more detail, and then we'll try to answer.
