### ISSUE TITLE
[bug] no `opt` executable in the `build` folder

### ISSUE THREAD

**Issue by jianguda** [google/souper#672]
Hey, we built latest souper yesterday, however, we can not found the `opt` executable in the `build` folder. We guess this should be one bug, please check this.

**Comment by regehr** [comment]
hi, opt is part of LLVM,not part of souper. you should find the opt executable here:
souper/third_party/llvm/Release-build/bin/opt
(or maybe Debug-build)

**Comment by jianguda** [comment]
thanks!
