### ISSUE TITLE
shared library fun

### ISSUE THREAD

**Issue by regehr** [google/souper#688]
Hi @LebedevRI I'm working on a branch here that factors some code out of souper2llvm so it can be reused in a different context:

  https://github.com/regehr/souper/tree/cost-model

To get the codegen shared library to work properly on OS X, I had to link it against the LLVM static libraries. I don't think there's any problem with that.

However, every program which loads both the souper opt pass and also the codegen library is now dying with this error:

```opt: CommandLine Error: Option 'verify-dom-info' registered more than once!```

Do you have ideas for how to work around this? Some solutions seem to be:
1. make the codegen library static instead of shared
2. duplicate some code instead of doing this refactoring
3. some better solution that I'm not aware of

I'm leaning towards (1) right now. Any thoughts?

**Comment by LebedevRI** [comment]
Only saw mention now.

I don't really have any insights to OSX,
but those errors do look like something i'd expect from multiple definitions.

I'm guessing no such issues were previously seen with just the souper opt pass?
Is there a version mismatch between the opt that plugin is being loaded into,
and the LLVM with which that plugin was built against?
