### ISSUE TITLE
Duplicate result

### ISSUE THREAD

**Issue by manasij7479** [google/souper#741]
Input:
%0:i32 = var
%1 = add %0, 1
%2 = and %1, 5
%3 = or %2, 42
%4 = add %3, 0
infer %4

Invocation:
souper-check -infer-rhs -souper-enumerative-synthesis -z3-path=/usr/bin/z3 -souper-enumerative-synthesis-num-instructions=1  -souper-check-all-guesses

(Result 1 and 3 are identical.)
Results:
; RHS inferred successfully
; result 1:
%0:i32 = var
%1:i32 = add 1:i32, %0
%2:i32 = and 5:i32, %1
%3:i32 = or 42:i32, %2
result %3

; result 2:
%0:i32 = var
%1:i32 = add 1:i32, %0
%2:i32 = and 5:i32, %1
%3:i32 = add 42:i32, %2
result %3

; result 3:
%0:i32 = var
%1:i32 = add 1:i32, %0
%2:i32 = and 5:i32, %1
%3:i32 = or 42:i32, %2
result %3

; result 4:
%0:i32 = var
%1:i32 = add 1:i32, %0
%2:i32 = and 5:i32, %1
%3:i32 = xor 42:i32, %2
result %3

**Comment by regehr** [comment]
hmm, weird. do you have time to look at this @zhengyangl ?

**Comment by zhengyangl** [comment]
yep.

**Comment by zhengyangl** [comment]
Well, the guess for `result 1` is generated from NOP synthesis, the `or` comes from %3 in LHS. And the guess for `result 3` is generated from ordinary enumeration, the `or` comes from synthesis. Are we going to fix this? @regehr

**Comment by manasij7479** [comment]
The fix (do not synthesize existing components) seems like it will take quite a bit of engineering effort.

**Comment by zhengyangl** [comment]
Change the type of RHSs from `vector` to `unordered_set` seems solve the issue.

**Comment by manasij7479** [comment]
That does not stop the redundant enumeration, I think.

**Comment by zhengyangl** [comment]
does this look good  https://github.com/google/souper/pull/742/files ? After this patch the dup is gone.

**Comment by zhengyangl** [comment]
@manasij7479 Each insts constructed relies on the foldingsetnode for internal caching, the guesses with the same DAG has with same pointers. But I am a little worried of the quality of implementation (see this line and below https://github.com/google/souper/blob/813f2879c3cbfd1f1c591e1f2f25f2f3e021e453/lib/Inst/Inst.cpp#L576). The code raised several bug previously.

**Comment by regehr** [comment]
interesting. thanks for reporting / looking into this one. I'm not yet sure about this fix-- we should test thoroughly.

**Comment by regehr** [comment]
hey but I have a different question: when we reuse components from the LHS on the RHS, are we reusing constants also? if so, maybe we should just stop doing that since we can synthesize any constant.

**Comment by zhengyangl** [comment]
@regehr yes, and yes, its a good idea.

**Comment by zhengyangl** [comment]
Ignore my last patch. The redundant should only happens between synthesized guesses and NOP guesses, right? We can just discard synthesized guess if the guess is a NOP.

**Comment by regehr** [comment]
ok-- not reusing constants should be a one-liner, want to roll that into your pull req?

**Comment by zhengyangl** [comment]
@regehr ,these are different and I will do it in another PR.

**Comment by regehr** [comment]
thanks!

**Comment by zhengyangl** [comment]
> hey but I have a different question: when we reuse components from the LHS on the RHS, are we reusing constants also? if so, maybe we should just stop doing that since we can synthesize any constant.

Oops, I misunderstood. It is *NOT* reusing constants.

**Comment by manasij7479** [comment]
Can we close this or is there something more to be done here?
