### ISSUE TITLE
does Souper play nice with X-ray?

### ISSUE THREAD

**Issue by victorstewart** [google/souper#801]
i wonder if you all have seen the llvm project x-ray? it works by inserting some nops (that get atomically replaced at runtime) at the head and tail of functions to enable tracing.

will souper eat these nops? lol

 ![image](https://user-images.githubusercontent.com/17534897/98519962-5ea95c00-2269-11eb-91f4-0778019ff1b1.jpeg)

![image](https://user-images.githubusercontent.com/17534897/98519986-6537d380-2269-11eb-931b-383060d3f51d.jpeg)

**Comment by regehr** [comment]
hi Victor, are these nops present at the IR level? if so, what do they look like? souper may well try to eat them, but it should not be hard to hack it to leave them alone.

**Comment by victorstewart** [comment]
@deanberris is the man to ask! but i can investigate.

**Comment by deanberris** [comment]
Yes they're only ever attributes to functions, so they don't look like instructions in IR. These attributes are interpreted when lowering to machine code so if souper looks at the generated machine code then this would be a problem.

**Comment by regehr** [comment]
souper works purely on IR and it leaves attributes alone, so I think we're all good here!
