### ISSUE TITLE
Assertion failed: (EB.get(&I)->hasOrigin(&I)), function ExtractExprCandidates, file .../lib/Extractor/Candidates.cpp, line 1025

### ISSUE THREAD

**Issue by ychen306** [google/souper#821]
Failed with this input

```llvm
; ModuleID = 'foo.ll'
source_filename = "sqlite3.c"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx10.15.0"

define internal fastcc void @yy_reduce() unnamed_addr {
sw.bb115:
  %sub.ptr.rhs.cast139 = ptrtoint i8* undef to i64
  %sub.ptr.sub140 = sub i64 undef, %sub.ptr.rhs.cast139
  %conv141 = trunc i64 %sub.ptr.sub140 to i32
  %bf.value145 = and i32 %conv141, 2147483647
  %bf.shl146 = shl i32 %bf.value145, 1
  store i32 %bf.shl146, i32* undef, align 8
  ret void
}
```

I ran with this command
```bash
~/workspace/souper/third_party/llvm-Release-install/bin/opt -load /Users/tom/workspace/souper/build/libsouperPass.dylib -souper -o /dev/null
```

The commit hash of souper is `16f145e1826f76090ace941fde7abf352ba36aa1`

**Comment by ychen306** [comment]
Seems like in https://github.com/google/souper/blob/main/lib/Extractor/Candidates.cpp#L1025,
the assertion should be

**Comment by regehr** [comment]
thanks for the bug report! I'll look at it Monday

**Comment by ychen306** [comment]
I ran souper at various places in the optimization pipeline instead of just at the end. My guess is that LLVM's typical optimization gets rid of this kind of patterns.

**Comment by regehr** [comment]
I'm somewhat satisfied with this explanation, but souper doesn't just run at the end. when you load it as an opt pass, it gets run 5 times, throughout the optimization pipeline. but it always runs after the same passes, so that could have hidden this issue!

**Comment by ychen306** [comment]
In my custom pipeline, I make sure souper is run before instcombine. Maybe that uncovered the issue.
