### ISSUE TITLE
[alive2] `IfNonPoison` removed upstream

### ISSUE THREAD

**Issue by ConnorBaker** [google/souper#864]
Upstream Alive2 removed `IfNonPoison` in https://github.com/AliveToolkit/alive2/commit/853523992d69e12552dd6ec2b4dc99c57172ea60. This will cause issues later when trying to use Souper with more recent versions of LLVM or Alive2.

The only use I found in Souper was here: https://github.com/google/souper/blob/0c8caa5ee1300d9634e8b226e5ec2a561958e153/lib/Infer/AliveDriver.cpp#L132

Is it enough to change it to `AndNonPoison`, or does the change in semantics mean that won't work?

**Comment by regehr** [comment]
hi! @manasij7479 is currently updating the version of alive2 used by souper to be the latest one, so I think we should just wait on that change. do you have an update on this Manasij?
