### ISSUE TITLE
Hi, Is this superoptimizer hardware irrelvant?

### ISSUE THREAD

**Issue by xshen053** [google/souper#873]
Hi, want to know is this superoptimizer hardware relvant or irrelvant.

**Comment by xshen053** [comment]
Oh, I mean will souper optimize differently on different target cpu, let make different optimization decision based on target. Like hardware-aware

**Comment by regehr** [comment]
no, it won't do anything like that, it works at the level of LLVM IR and has no specific knowledge of the target

**Comment by regehr** [comment]
you might look instead at this project, however https://github.com/minotaur-toolkit/minotaur

**Comment by xshen053** [comment]
Thank you, yes, minotaur! The problem is I am working on arm specific, so probably need to figure out how to move minotaur on arm.
